version: "3.9"

services:

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

  simulator:
    build: .
    command: python simulator.py

    depends_on:
      - redis

    environment:
      REDIS_HOST: redis

  api:
    build: .
    command: uvicorn src.api.explainability_api:app --host 0.0.0.0 --port 8000

    depends_on:
      - redis

    environment:
      REDIS_HOST: redis

    ports:
      - "8000:8000"

  prometheus-exporter:
    build: .
    command: python src/monitoring/prometheus_exporter.py

    depends_on:
      - redis

    environment:
      REDIS_HOST: redis

    ports:
      - "9101:9101"

  scoring-consumer:
    build: .

    command:
      - python
      - src/consumers/scoring_consumer.py
      - --config
      - config/rules/baseline.yaml
      - --consumer
      - scoring_worker_1

    depends_on:
      - redis

    environment:
      REDIS_HOST: redis

    deploy:
      replicas: 10

  monitoring-consumer:
    build: .

    command: python src/monitoring/monitoring_consumer.py

    depends_on:
      - redis

    environment:
      REDIS_HOST: redis

    deploy:
      replicas: 4

  feedback-consumer:
    build: .

    command: python src/feedback/feedback_consumer.py

    depends_on:
      - redis

    environment:
      REDIS_HOST: redis

    deploy:
      replicas: 4

  prometheus:
    image: prom/prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana

    depends_on:
      - prometheus

    ports:
      - "3001:3000"

    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: